// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iudzwslvdgknfmsikxpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1ZHp3c2x2ZGdrbmZtc2lreHB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzAzMTAsImV4cCI6MjA2NTc0NjMxMH0.Ml5qUNTw4v8ebBKawVhoBcXqT7aAUol3u0fa7LtVmW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);